
	<div class="row ">
  <div  class="Span10 pagination-centered" >
	<div class="btn-toolbar" style="margin: 0;">
	
	<div class="btn-group">
    <button class="btn btn-large" ><?php echo anchor('estate/preview/0/2','Business'); ?></button>
    <button class="btn btn-large dropdown-toggle" data-toggle="dropdown">
    <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
	<li><?php echo anchor('estate/preview/0/0','Sales'); ?></li>
	<li><?php echo anchor('estate/preview/1/1','Rents'); ?></li>
    </ul>
    </div>
	
	<div class="btn-group">
    <button class="btn btn-large"><?php	echo anchor('estate/preview/1/2','Residence'); ?></button>
    <button class="btn btn-large dropdown-toggle" data-toggle="dropdown">
    <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
	<li><?php echo anchor('estate/preview/1/0','Sales'); ?></li>
	<li><?php echo anchor('estate/preview/1/1','Rents'); ?></li>
    </ul>
    </div>
	
	</div>
</div>
</div>
   